---
swagger: '2.0'
info:
  version: 1.0.0
  title: Hangman
  description: |
    API for playing the Hangman game
schemes:
  - http
host: localhost
basePath: /v1
paths:
  /game:
    post:
      summary: Create a new game
      description: Create a new game
      responses:
        200:
          description: id of the newly-created game
          schema: 
            type: object
            properties:
              game_id:
                type: integer
              
              